### ISSUE TITLE
jsus 0.3.5 gemspec is broken (because it was built using Ruby 1.9)

### ISSUE THREAD

**Issue by michaelklishin** [jsus/jsus#2]
jsus 0.3.5 gemspec is broken because the gem was built on Ruby 1.9 (that has freaking buggy YAML parser):

```
Invalid gemspec in [/Users/antares/.rvm/gems/…/specifications/jsus-0.3.5.gemspec]: Illformed requirement ["#<YAML::Syck::DefaultKey:0x6ad1c> 1.0.3"]
Invalid gemspec in [/Users/antares/.rvm/gems/…/specifications/jsus-0.3.5.gemspec]: Illformed requirement ["#<YAML::Syck::DefaultKey:0x6ad1c> 1.0.3"]
```

Another proof can be seen on rubygems.org:

![](https://img.skitch.com/20110917-kfrp53ak4n42fee7u6xrmu119d.jpg)

Please use 1.8 when you do gem build.

**Comment by markiz** [comment]
Thanks. Should be ok for 0.3.6 http://rubygems.org/gems/jsus/versions/0.3.6

Damn, I have forgotten to add myself to notification list for issues.
